spring.application.name=smart-service-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_service_db
spring.datasource.username=postgres
spring.datasource.password=Omm@3132

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080